### ISSUE TITLE
Define website top navigation menu

### ISSUE THREAD

**Issue by kraulain** [FreeJavaBootcamp/fjb-website#2]
### Background

The website currently has a default navigation bar that does not reflect the structure and content we wish to have.
We need to update the menu to have clear links to the needed pages and create empty pages for each menu item that will later hold the content. 

---

### Requirements

- Add a menu with the following menu items: Home (FJB logo and text), About, Workshops, Projects, Community, Contact
- Update the repository structure to have dummy pages for each menu item.
- Update the project readme to include a description of the project structure.

---

### Resources
 
- [JBake Documentation](https://jbake.org/docs/2.6.7/)

**Comment by Wandji69** [comment]
I am picking this up

**Comment by kraulain** [comment]
Thanks for the good work @Wandji69 
Here are a few improvements that would help.

- ignored files in `/output` need to be remove
- `Workshops` menu should come before `Projects` menu
- The logo could be more vertically centered in the menu bar
- No need for an explicit `Home` menu
- The readme need to be updated to present something like a site tree showcasing this new structure.

I will get started on some of this right away but feel free to let me know if you are free to do some of the updates
